---
title: "Crotty8day"
author: "Xulong Wang"
date: "January 25, 2016"
output: pdf_document
---

```{r, include = F}

library(affy)
library(oligo)
library(ape)
library(amap)
library(xlsx)
library(genefilter)
library(org.Mm.eg.db)
library(TxDb.Mmusculus.UCSC.mm10.knownGene)
library(preprocessCore)
library(qvalue)
library(dplyr)
library(tidyr)
library(reshape)
library(Biobase)

rm(list = ls())
source("~/Dropbox/GitHub/X/function.R")
setwd("~/Dropbox/GitHub/Il21/Crotty2015")

```

# TPM

```{r}

load("../data/myTpm.rdt")
myTpm[rowMax(as.matrix(myTpm)) > 1e4, ]
myTpm <- myTpm[! rowMax(as.matrix(myTpm)) > 1e4, ]
myTpm <- sweep(myTpm, 2, colSums(myTpm), "/") * 1e6 
myTpm <- log2(myTpm + 1)
myTpm <- myTpm[rowMax(as.matrix(myTpm)) > 5, ]

# group <- gsub("[12]", "", names(myTpm))
# aov.pval <- apply(myTpm, 1, function (x) summary(aov(x ~ group))[[1]][["group", "Pr(>F)"]])
# myTpm <- myTpm[aov.pval < 0.05, ]
# myTpm_mean <- data.frame(NN = rowMeans(myTpm[1:2]), NP = rowMeans(myTpm[3:4]), PP = rowMeans(myTpm[5:6]))
# colSums(myTpm_mean)

```

# Crotty's 8 days

```{r}

cel.files <- read.celfiles(list.celfiles("GSE21380_CEL/", full.name = T))
eight <- exprs(rma(cel.files))

file <- "Mouse430_2.na35.annot.csv.gz"
mouse430 <- read.table(file, header = T, comment.char = "#", sep = ",", stringsAsFactors = F)
mouse430 <- mouse430[c("Probe.Set.ID", "Gene.Symbol")]
mouse430$Gene.Symbol <- gsub(" .*", "", mouse430$Gene.Symbol)

eight <- eight[mouse430$Probe.Set.ID, ]
eight <- apply(eight, 2, function(x) tapply(x, mouse430$Gene.Symbol, max))
colnames(eight) <- c("NonTFH_Rep1", "NonTFH_Rep2", "TFH_Rep1", "TFH_Rep2", "GCTFH_Rep1", "GCTFH_Rep2", "Naive_CD4_T")
eight <- eight[-1, ] %>% as.data.frame

eight_mean <- data.frame(TH1 = rowMeans(eight[1:2]), TFH = rowMeans(eight[3:4]), GCTFH = rowMeans(eight[5:6]), NV = eight[7])

```

# BATCH CORRECTION

```{r}

data <- inner_join(add_rownames(myTpm, "gene"), add_rownames(eight, "gene"))
data <- inner_join(add_rownames(myTpm_mean, "gene"), add_rownames(eight_mean, "gene"))

data <- data.frame(row.names = data$gene, data[-1])
colSums(data)

dt.ctr <- data - rowMeans(data)
dt.svd <- svd(dt.ctr) # SVD
barplot(dt.svd$v[, 1]) # PC1

dt2 <- t(apply(dt.ctr, 1, function (x) {lm(x ~ dt.svd$v[, 1])$res})) 
dt3 <- dt2 + rowMeans(data)

```

# Clutering

```{r}

hc1 <- hcluster(t(dt3), method = "pearson", link = "average")

pdf("./phylo8d.pdf", width = 6, height = 5)

plot(as.phylo(hc1), edge.width = 2, font = 2, label.offset = 1e-4)

dev.off()

```
